import Header from "./components/atoms/header";
import Toast from "./components/atoms/toast";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import QueryContext from "./contexts/QueryContext";
import AuthContext from "./contexts/AuthContext";
import { ThemeProvider } from "@/components/ThemeProvider";
import ThemeToggle from "@/components/ThemeToggle";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Toast/>
          <AuthContext>
            <QueryContext>
              <div className="min-h-full">
                  <Header/>
                {children}
              </div>
            </QueryContext>
          </AuthContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
